### ISSUE TITLE
🎁Adjust ranking in solrconfig.xml based on UTK specifications

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#424] opened 2023-06-07 17:44 UTC
# Summary
related to
- #408 
- #392

Notes from Crystal on ranking:
Ranking
* It is an algorithm
  * The fields (i.e. title, description, etc.) that show the search term all have different points associated with it (i.e. title = 1, description = 3)
    * Item with the most points sorts to the top of the results
* We need client to tell us which document should show higher and then we go and search tune using this algorithm
  * Ask to prioritize the terms
  * If they change their metadata fields, tuning will need to happen again
* Lea Ann is knowledgeable on this

We will pair with Mark, to look at default and make adjustments.

# Acceptance Criteria
- [ ] Ranking specifications are established from UTK
- [ ] Ranking matches UTK specifications

**Comment by jillpe** [comment] 2023-07-07 18:39
A breakdown of solr config in the pairing with UTK would be helpful for them

**Comment by jillpe** [comment] 2023-07-10 14:37
related to
- #408

**Comment by jillpe** [comment] 2023-07-10 14:53
Mark and Josh are point of contacts to pair with on this ticket

**Comment by jillpe** [comment] 2023-07-11 17:49
Possibly helpful: https://playbook-staging.notch8.com/en/dev/how-to/update-solr-configset

**Comment by ShanaLMoore** [comment] 2023-07-19 15:02
## Next Steps 

@jillpe to set up pairing time with Mark and the team. We may want to pull in LeaAnn for guidance with this discussion too.

**Comment by jillpe** [comment] 2023-07-20 15:28
Pairing set up for Thursday 7/27

Notes from Lea Ann:

**What does ranking accomplish?**
- Helps tune search results, so they appear in the order you'd expect
- Assigns points to metadata fields, where the search term could exist
  - More points are given to the fields you want prioritized as most relevant
- When a search is made, for each work, solr finds every field that term exists and adds the combined points
  - They are then displayed from highest amount of points to lowest
- You can rank via query fields (qf) and/or phrase fields (pf)

**How do you test the changes**
- Should NOT require a reindex
- Find 2-3 works that have the same search term but with a variation of which fields it displays in 
  - Determine the order they should be displayed in by adding the points up yourself
- Make sure they display in that order

**Important to Note**
- Ranking is not an exact science and there is a ton of nuance. Other processes happen in solr that will affect search results. You need to tune search results over time because the user needs to use it for a while to find patterns they like/dislike. 

**Questions to ask client**
- What do you not like about the search results?
- Try to get an idea of what they expect the results to look like
  - Use an example search term as an example and get what they like/dislike from that
  
**Code Notes**
- This has been done in oral histories
  - Blacklight app, so solr folder is in a different location
- Located in solrconfig.xml for hyrax app
<details><summary>Screenshot of example code</summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/06e31957-5829-4cb1-9d68-c0881eb0b19e)


</details>

**Comment by ShanaLMoore** [comment] 2023-07-26 16:13
maybe helpful references

https://gitlab.com/notch8/oral_history/-/issues/11
https://gitlab.com/notch8/oral_history/-/merge_requests?scope=all&state=merged&search=boost

<img width="845" alt="image" src="https://github.com/scientist-softserv/utk-hyku/assets/10081604/c2b53ca4-4a9e-4051-8e1d-ec5d63a89ab7">

PR: https://github.com/scientist-softserv/oral-history/commit/fdb2891eba2f10505c529a3b626baa7c8890d5de

https://gitlab.com/notch8/oral_history/-/issues/1
https://gitlab.com/notch8/oral_history/-/merge_requests/37/diffs

**Comment by ShanaLMoore** [comment] 2023-07-26 22:34
https://lucidworks.com/post/use-solr-boost-function/

https://github.com/scientist-softserv/atla_digital_library/blob/main/solr/conf/solrconfig.xml

TODO: figure out why the changes aren't being applied.

**Comment by ShanaLMoore** [comment] 2023-07-27 17:24
If the requirements change to stemming, ref: https://github.com/scientist-softserv/utk-hyku/blob/main/solr/conf/schema.xml#L139

needs to be added to: https://github.com/scientist-softserv/utk-hyku/blob/main/solr/conf/schema.xml#L107-L113

Use solr dashboard analyze to confirm changes. this may require removing solr container and reindexing.

LaRita was successful at getting this to work locally but had issues reindexing w fedora.

**Comment by jillpe** [comment] 2023-07-27 17:58
confirmed via meeting with client 2023-07-27, we will be swapping the ranking requirement for a stemming requirement (Milestone 3). [Stemming SOW ticket](https://github.com/scientist-softserv/utk-hyku/issues/502). Closing this ticket.

**Closed as completed** 2023-07-27 18:00 UTC
Labels: Blocked, Pre-Launch, Search
