### ISSUE TITLE
Manually add additional properties to Collection

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#114] opened 2022-10-18 21:38 UTC
Per our last iteration meeting on 10/11/2022, the client agreed to not make allinson flex work with Collections. 

We will manually be adding any additional properties needed, to the Collection model.

Manually adding the collection metadata will allow us to still have the default behavior that comes with collections in hyrax, such as the collections show pages, and the search in collections

ref: notes from meeting - https://docs.google.com/document/d/18Bp1_mdXcVtFq1h8-nGA_97LL4n1YPO1TSX4rxweRCc/edit#

ref: notes from flex meeting - https://docs.google.com/document/d/1fQ2XOSR1Dww6JEtk0Q5F-uJB136OKyEcD-HNoPfIqt0/edit#heading=h.t2h1esit84hv

**Comment by DiemBTran** [comment] 2022-11-16 20:37
duplicate of #126

**Closed as completed by DiemBTran** 2022-11-16 20:37 UTC
