### ISSUE TITLE
set parent thumbnail (job)

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#381] opened 2023-03-30 09:15 UTC
# Story

Given the UTK's work structure (parent work has an attachment which owns the file_sets), the parent works do not have a thumbnail. 

We need to make the parent work have a thumbnail. Additionally, when clicking on the parent work, its UV should display its attachment (child works) and their file_sets.

# Acceptance Criteria 
The following should automatically happen when importing works via bulkrax, by introducing a new job. (Future thought -- should we make a UI component so the user can trigger this themselves? Because if they manually create works, it would not runt through Bulkrax jobs)

- [ ] parent work is does not require a file upload. It will not have a thumbnail if the parent doesn't upload one. ref: https://github.com/samvera/hyrax/blob/74d80612ae58c6d034d1ee192f608a4a2e20147f/lib/generators/hyrax/templates/config/initializers/hyrax.rb#L108
- [ ] when the parent work doesn't have a file, but it has an attachment/child work with file_sets, its thumbnail should match it's child's thumbnail
- [ ] the parent UV should display its child works and their file sets, even when the parent work doesn't have its own file.

# Screenshots / Video

![Image](https://user-images.githubusercontent.com/10081604/228788937-94ea37f8-b03d-431d-96d5-13b5be16d10d.png)

![image](https://user-images.githubusercontent.com/10081604/228793453-98c35012-28d3-4b06-a37f-3d942e5cc422.png)

# Testing Instructions and Sample Files

-

# Notes

LOUISVILLE had a similar set up, where the parent work did not have a thumbnail. They wanted it set to the first child's first file_set. 

We created a job: https://github.com/scientist-softserv/louisville-hyku/blob/main/lib/tasks/set_parent_thumbnail.rake

We created a rake task for them to manually run: https://github.com/scientist-softserv/louisville-hyku/blob/main/app/jobs/set_default_parent_thumbnail_job.rb

RELATED TO #369

**Comment by jillpe** [comment] 2023-06-26 21:30
duplicate of #438

**Closed as completed by jillpe** 2023-06-26 21:30 UTC
Labels: Theme Work, Pre-Launch
